version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      main:
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact-broker:
    image: pactfoundation/pact-broker
    container_name: pact-broker
    networks:
      main:
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_PORT: "9292"
      PACT_BROKER_DATABASE_ADAPTER: "postgres"
      PACT_BROKER_DATABASE_USERNAME: "postgres"
      PACT_BROKER_DATABASE_PASSWORD: "password"
      PACT_BROKER_DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_LOG_LEVEL: "debug"
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      PACT_BROKER_BASE_URL: "https://localhost http://localhost http://localhost:9292 http://pact-broker:9292"
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http
      PACT_BROKER_WEBHOOK_HTTP_METHOD_WHITELIST: "POST"
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: "/.*/"

  jenkins:
    build:
      dockerfile: Dockerfile
    networks:
      main:
    ports:
      - "8080:8080"
    container_name: jenkins
    # uncomment for docker in docker
    # privileged: true
    volumes:
      - jenkins-data:/var/jenkins_home

networks:
  main:
volumes:
  postgres-volume:
  jenkins-data:
